FATAL CARTOGRAPHER MEMORY LEAKAGE
System.OutOfMemoryException: Out of memory
at (wrapper dynamic-method) Verse.AI.Pawn_PathFollower.Verse.AI.Pawn_PathFollower.PatherTick_Patch3(Verse.AI.Pawn_PathFollower)
at (wrapper dynamic-method) Verse.Pawn.Verse.Pawn.Tick_Patch3(Verse.Pawn)
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Exception ticking Cartographer812825 (at (188, 0, 62)): System.OutOfMemoryException: Out of memory
at (wrapper dynamic-method) Verse.Pawn.Verse.Pawn.Tick_Patch3(Verse.Pawn)
at (wrapper dynamic-method) Verse.TickList.Verse.TickList.Tick_Patch2(Verse.TickList)
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

-----

Fixed game-crashing error. The Cartographer is apparently doing something that the game cannot solve and is causing RAM memory leakage.

This means that excess data just keeps building on the RAM until the entire computer runs out of memory and forces "Rimworld" to crash to the desktop in order to save the PC from overheating and later catching on fire.